# Generated by Django 3.2 on 2021-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='/images/defaultzzz.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='story_line',
            field=models.TextField(default='NOT AVAILABLE', max_length=1024),
        ),
    ]
