# Generated by Django 3.2 on 2021-07-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_handler', '0002_auto_20210705_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
    ]
